# .github/dependabot.yml
version: 2
updates:
  # 1. GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "chore"
      include: "scope"

  # 2. Docker (Updates base images in docker-compose.yml)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "chore"
      include: "scope"